// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9hQvggZWptxukkRdgtRfM3nt2nuf-wY0',
    appId: '1:460675135705:web:f01170b9cacd4df66866c8',
    messagingSenderId: '460675135705',
    projectId: 'jobgodsusers-1e8f5',
    authDomain: 'jobgodsusers-1e8f5.firebaseapp.com',
    storageBucket: 'jobgodsusers-1e8f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb2ipAcK2VK8XDzWC36-t-m4BSakqPSPw',
    appId: '1:460675135705:android:9f58a33a153174546866c8',
    messagingSenderId: '460675135705',
    projectId: 'jobgodsusers-1e8f5',
    storageBucket: 'jobgodsusers-1e8f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-FxUEtZSfvdPTZn8WExIHQTz1MYYs5KQ',
    appId: '1:460675135705:ios:dee919f3f7b14fa86866c8',
    messagingSenderId: '460675135705',
    projectId: 'jobgodsusers-1e8f5',
    storageBucket: 'jobgodsusers-1e8f5.appspot.com',
    iosBundleId: 'com.example.jobgods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-FxUEtZSfvdPTZn8WExIHQTz1MYYs5KQ',
    appId: '1:460675135705:ios:55a09dfd28f6a4556866c8',
    messagingSenderId: '460675135705',
    projectId: 'jobgodsusers-1e8f5',
    storageBucket: 'jobgodsusers-1e8f5.appspot.com',
    iosBundleId: 'com.example.jobgods.RunnerTests',
  );
}
